In [1]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv('police.csv')

In [42]:
data.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [4]:
data.isna().any()

stop_date             False
stop_time             False
county_name            True
driver_gender          True
driver_age_raw         True
driver_age             True
driver_race            True
violation_raw          True
violation              True
search_conducted      False
search_type            True
stop_outcome           True
is_arrested            True
stop_duration          True
drugs_related_stop    False
dtype: bool

In [5]:
data.isna().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [43]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
91736    False
91737    False
91738    False
91739    False
91740    False
Length: 91741, dtype: bool

In [44]:
data[data.duplicated()]

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
16,2005-07-19,00:30,NaN,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
104,2005-10-03,13:26,NaN,M,1975.0,30.0,Black,Speeding,Speeding,False,NaN,Arrest Driver,True,30+ Min,False
117,2005-10-04,00:36,NaN,M,1961.0,44.0,White,Special Detail/Directed Patrol,Other,False,NaN,Arrest Driver,True,30+ Min,False
149,2005-10-05,10:00,NaN,M,1981.0,24.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
239,2005-10-08,12:30,NaN,M,1978.0,27.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89720,2015-10-03,22:59,NaN,F,1968.0,47.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
89873,2015-10-10,08:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
90047,2015-10-16,20:37,NaN,F,1986.0,29.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,16-30 Min,False
90136,2015-10-20,11:47,NaN,M,1971.0,44.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,16-30 Min,False
90583,2015-11-05,03:14,NaN,M,1947.0,68.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [45]:
data.drop_duplicates(inplace = True)

In [46]:
data[data.duplicated()]

Empty DataFrame
Columns: [stop_date, stop_time, county_name, driver_gender, driver_age_raw, driver_age, driver_race, violation_raw, violation, search_conducted, search_type, stop_outcome, is_arrested, stop_duration, drugs_related_stop]
Index: []

In [13]:
data.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [27]:
data['stop_duration'] = data['stop_duration'].str.replace('Min','')
data.head(10)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
5,2005-03-23,09:45,NaN,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15,False
6,2005-04-01,17:30,NaN,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
7,2005-06-06,13:20,NaN,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
8,2005-07-13,10:15,NaN,M,1970.0,35.0,Black,Speeding,Speeding,False,NaN,Citation,False,0-15,False
9,2005-07-13,15:45,NaN,M,1970.0,35.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False

In [29]:
data.nunique()

stop_date             3768
stop_time             1436
county_name              0
driver_gender            2
driver_age_raw          97
driver_age              78
driver_race              5
violation_raw           12
violation                6
search_conducted         2
search_type             24
stop_outcome             6
is_arrested              2
stop_duration            5
drugs_related_stop       2
dtype: int64

In [37]:
data.sort_values(by = ['stop_time', 'driver_age']).head(20)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
40,2005-10-01,00:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30,True
41,2005-10-01,00:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+,True
1865,2005-12-03,00:00,NaN,M,1988.0,17.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
7576,2006-06-18,00:00,NaN,M,1989.0,17.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30,False
73853,2013-12-30,00:00,NaN,F,1996.0,17.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
6911,2006-05-28,00:00,NaN,M,1988.0,18.0,Black,Speeding,Speeding,False,NaN,Citation,False,0-15,False
7363,2006-06-12,00:00,NaN,M,1988.0,18.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
54621,2011-12-14,00:00,NaN,M,1993.0,18.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
68724,2013-05-05,00:00,NaN,M,1995.0,18.0,Hispanic,Seatbelt Violation,Seat belt,False,NaN,Citation,False,0-15,False
538,2005-10-22,00:00,NaN,M,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
5856,2006-04-21,00:00,NaN,M,1987.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30,False
11479,2006-11-03,00:00,NaN,M,1987.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
5337,2006-04-04,00:00,NaN,M,1986.0,20.0,Black,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15,False
11772,2006-11-12,00:00,NaN,M,1986.0,20.0,White,Speeding,Speeding,False,NaN,N/D,False,0-15,False
62004,2012-07-19,00:00,NaN,F,1992.0,20.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15,False
67277,2013-02-28,00:00,NaN,M,1993.0,20.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15,False
3185,2006-01-20,00:00,NaN,M,1985.0,21.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15,False
3894,2006-02-11,00:00,NaN,M,1985.0,21.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15,False
7918,2006-07-02,00:00,NaN,F,1985.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False
8340,2006-07-16,00:00,NaN,M,1985.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15,False

In [38]:
data['driver_age'].max(),data['driver_age'].min()

(99.0, 15.0)